### ISSUE TITLE
Bug in setAge()

### ISSUE THREAD

**Issue by cdmuir** [DomBennett/treeman#5]
If I understand what the function should be doing, I think it should be:

function (tree, val) 
{
    tree_age <- getAge(tree)
    spns <- getNdsSlt(tree, ids = tree@all, slt_nm = "spn")
    # spns <- spns/(tree_age) # previous, incorrect
    spns <- spns * val / tree_age
    tree <- setNdsSpn(tree, ids = tree@all, vals = spns)
    tree
}

**Comment by DomBennett** [comment]
Yes, it should. Thank you!

Now corrected in the latest dev version.
