### ISSUE TITLE
order of nodes in @nds

### ISSUE THREAD

**Issue by csmiguel** [DomBennett/treeman#6]
The order of the nodes in the @nds slot is different that the order they have in the @ndlst. This issue can lead to errors when working with treeman objects, as almost happens to me.

**Comment by DomBennett** [comment]
Hi @csmiguel,

Do you have a reproducible example of where this occurred?

Thanks

**Comment by csmiguel** [comment]
Hi @DomBennett ,
Thanks for answering.
Download tree:
https://www.dropbox.com/s/w9biajid3rvfo2j/phylo_tree.rds?dl=0
```
library(dplyr)
library(treeman)
#it happens when converting a phylo tree to treeman.
tree <- readRDS("phylo_tree.rds")
#notice the order:
as(tree, "TreeMan")@ndlst %>% names() %>% grep(pattern = "n", value = T)
as(tree, "TreeMan")@nd
```

**Comment by DomBennett** [comment]
OK -- Thanks!

Do you have an example where this ordering would cause you a bug? I might be able to recommend a coding approach.

Just FYI...
The package makes no attempt to ensure that the order is consistent between ape's `phylo` objects and treeman's `TreeMan` object. Additionally, all treeman functions should not be relying on node order in any way. They all work by node ids.

**Comment by csmiguel** [comment]
Thanks for the clarification. The package does a great job for preventing errors. Sorry for the confusion. Great package.

**Comment by DomBennett** [comment]
One solution might be to write out your `phylo` object as a Newick file with node labels and then read the tree in again with treeman.

These pages describe how you might this:
- https://github.com/DomBennett/treeman/wiki/Reading-and-writing
- (and then the inverse) https://github.com/DomBennett/treeman/wiki/Writing-in-Newick-with-ndLabels()

Let me know if you have any more problems. I'll close this issue for now.
